<?php

function total_adder_plus_menu() {
  $items['total_adder_plus'] = array(
    'title' => 'Total Adder Plus',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('total_adder_plus_form'),
    'access callback' => 'user_is_logged_in'
  );
  return $items;
}

function total_adder_plus_form($form, &$form_state) {
  $form['adder_term1'] = array(
    '#type' => 'textfield',
    '#title' => t('Some number'),
    '#size' => 10,
    '#required' => true
  );
  
  $form['adder_term2'] = array(
    '#type' => 'textfield',
    '#title' => t('Another number'),
    '#size' => 10,
    '#required' => true
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit')
  );
  
  return $form;
}
