<?php

function total_adder_plus_menu() {
  $items['total_adder_plus'] = array(
    'title' => 'Total Adder Plus',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('total_adder_plus_form'),
    'access callback' => 'user_is_logged_in'
  );
  return $items;
}

function total_adder_plus_form($form, &$form_state) {
  $form['adder_term1'] = array(
    '#type' => 'textfield',
    '#title' => t('Some number'),
    '#size' => 10,
    '#required' => true
  );
  
  $form['adder_term2'] = array(
    '#type' => 'textfield',
    '#title' => t('Another number'),
    '#size' => 10,
    '#required' => true
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit')
  );
  
  return $form;
}

function total_adder_plus_form_submit($form_id, &$form_state) {
  $term1 = $form_state['values']['adder_term1'];
  $term2 = $form_state['values']['adder_term2'];
  
  drupal_set_message(t('@term1 + @term2 = @total', array(
    '@term1' => $term1,
    '@term2' => $term2,
    '@total' => $term1 + $term2
  )));
}

function total_adder_plus_form_validate($form, &$form_state) {
  $term1 = $form_state['values']['adder_term1'];
  
  if(!is_numeric($term1)) {
    form_set_error('adder_term1', t('@title field must be a number.', array(
      '@title' => $form['adder_term1']['#title']
    )));
  }
  
  $term2 = $form_state['values']['adder_term2'];
  
  if(!is_numeric($term2)) {
    form_set_error('adder_term2', t('@title field must be a number.', array(
      '@title' => $form['adder_term2']['#title']
    )));
  }
}
